"""
ANTLR Generated Code Directory

This directory contains parser code automatically generated by ANTLR4.
These files should not be manually edited, they are automatically generated during package build.

If cloning from Git, you need to run the generation script first:
    ./scripts/generate_parser.sh
"""

# Export main classes for external use
# If files don't exist (cloned from Git but not generated), ImportError will be raised
# This is expected behavior, prompting users to run the generation script first
try:
    from .HiveLexer import HiveLexer
    from .HiveParser import HiveParser
    from .HiveParserVisitor import HiveParserVisitor
    from .HiveParserListener import HiveParserListener
    
    __all__ = [
        "HiveLexer",
        "HiveParser",
        "HiveParserVisitor",
        "HiveParserListener",
    ]
except ImportError as e:
    raise ImportError(
        "ANTLR generated code not found.\n"
        "If cloning from Git, please run first:\n"
        "  ./scripts/generate_parser.sh\n"
        "Or install ANTLR4 tool and run the generation script."
    ) from e
